// Generated by cbindgen — do not edit by hand.

#ifndef MEOW_CORE_H
#define MEOW_CORE_H

#pragma once

/* Regenerate with `cbindgen --config cbindgen.toml --output include/meow_core.h` */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C-compatible egress callback. Called from the tun2socks tokio runtime
 * whenever tun2socks produces a packet bound for Swift's `NEPacketTunnelFlow`.
 * Swift guarantees `ctx` remains live between `meow_tun_start` and
 * `meow_tun_stop`.
 */
typedef void (*MeowWritePacket)(void *ctx, const uint8_t *data, uintptr_t len);

/**
 * Initialize logging. Safe to call more than once.
 */
void meow_core_init(void);

/**
 * Emit a log line from the NetworkExtension host (ObjC) into the same tracing
 * pipeline the engine uses, so NE lifecycle events — start/stop, sleep/wake,
 * `reasserting`, errors — land in the App Group file log (and os_log, and the
 * REST `/logs` stream) interleaved with engine output on one timeline.
 *
 * `level`: 0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace; anything else
 * is treated as info. No-op on a NULL or non-UTF-8 `msg`.
 *
 * # Safety
 * `msg` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void meow_core_log(int level, const char *msg);

/**
 * Set the app-group container path where config.yaml and cache files live.
 * `dir` may be NULL or empty.
 *
 * Also exports `$XDG_CONFIG_HOME=<dir>` into the process env so `meow-config`
 * finds its GeoIP database at `<dir>/meow/Country.mmdb` (upstream meow's
 * resolution order is `$XDG_CONFIG_HOME/meow/` → `$HOME/.config/meow/`).
 * iOS sandbox HOME has no `.config`, so the env var is how the bundled Country.mmdb
 * lands on the engine's load path.
 *
 * # Safety
 * `dir` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void meow_core_set_home_dir(const char *dir);

/**
 * Return the last error message for the calling thread. The pointer is
 * owned by the crate and valid until the next error is set on the same
 * thread — copy immediately if retention is needed.
 */
const char *meow_core_last_error(void);

/**
 * Start the meow-rs engine using the YAML at `config_path`. Idempotent.
 * Returns 0 on success, -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `config_path` must point to a NUL-terminated UTF-8 string.
 */
int meow_engine_start(const char *config_path);

/**
 * Stop the meow-rs engine. Idempotent.
 */
void meow_engine_stop(void);

/**
 * Returns 1 if the engine is running, 0 otherwise.
 */
int meow_engine_is_running(void);

/**
 * Validate a Clash YAML config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `yaml` must point to `len` bytes of UTF-8.
 */
int meow_engine_validate_config(const char *yaml, int len);

/**
 * Return the number of currently active (in-flight) TCP flows dispatched
 * through the tun2socks layer. Useful for diagnosing connection accumulation.
 */
int64_t meow_active_tcp_conns(void);

/**
 * Write cumulative upload/download byte counters. Safe to call before
 * `meow_engine_start` — returns zero counters.
 *
 * # Safety
 * Pointers, if non-NULL, must reference writable 64-bit integer slots.
 */
void meow_engine_traffic(int64_t *out_upload, int64_t *out_download);

/**
 * Convert a subscription body (Clash YAML, or base64-wrapped / plain v2rayN
 * URI list) to Clash YAML. Writes NUL-terminated UTF-8 into `out`/`out_cap`.
 * Returns the total bytes needed (not counting NUL); if the return exceeds
 * `out_cap`, the output was truncated — allocate `ret + 1` and retry.
 * Returns -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `body` must reference `len` bytes; `out` must reference `out_cap` bytes
 * if non-NULL.
 */
int meow_engine_convert_subscription(const char *body, int len, char *out, int out_cap);

/**
 * Measure direct TCP connect latency to `host:port`. Writes elapsed ms into
 * `out_ms`; returns 0 on success, -1 on error.
 *
 * # Safety
 * `host` must be NUL-terminated; `out_ms` must be writable.
 */
int meow_engine_test_direct_tcp(const char *host, int port, int timeout_ms, int64_t *out_ms);

/**
 * HTTP reachability via the engine's default (direct) adapter.
 *
 * # Safety
 * `url` must be NUL-terminated; outputs may be NULL.
 */
int meow_engine_test_proxy_http(const char *url, int timeout_ms, int *out_status, int64_t *out_ms);

/**
 * Resolve `host` via the engine resolver. Writes comma-separated IPs into
 * `out`/`out_cap` (same truncation rules as `meow_engine_convert_subscription`).
 *
 * # Safety
 * `host` must be NUL-terminated; `out` must reference `out_cap` bytes if
 * non-NULL.
 */
int meow_engine_test_dns(const char *host, int timeout_ms, char *out, int out_cap);

/**
 * Select a member proxy inside a `type: select` group, in-process —
 * the same mutation that `PUT /proxies/{group}` performs against the
 * REST API, but without the loopback hop. `group` and `name` are
 * matched against the upstream `SelectorGroup` byte-for-byte: no
 * Unicode normalization, no percent-decoding, no whitespace folding.
 * Emoji + CJK + space names therefore round-trip verbatim from YAML
 * to selector lookup, eliminating a class of bugs the URL-encoded
 * path is sensitive to.
 *
 * Return codes:
 * * `0`  — selection applied.
 * * `-1` — argument is null or not valid UTF-8.
 * * `-2` — engine is not running.
 * * `-3` — group not found, or the named proxy is not a select group.
 * * `-4` — `name` is not a member of the selector.
 *
 * On non-zero returns, `meow_core_last_error` carries a sanitized
 * reason suitable for surfacing in the UI.
 *
 * # Safety
 * `group` and `name` must each be a NUL-terminated UTF-8 C string.
 */
int meow_proxy_select(const char *group, const char *name);

/**
 * Patch a Clash YAML config for iOS: strips `dns` and `subscriptions`;
 * pins `mixed-port`; injects a hardened `external-controller` (random
 * loopback port) + random bearer `secret`; injects `geox-url` when absent.
 * Writes NUL-terminated UTF-8 into `out`/`out_cap`. Returns bytes needed (excl
 * NUL) on success; callers allocate `ret + 1` and retry if `ret >= out_cap`.
 * Returns -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `source_yaml` must be NUL-terminated UTF-8. `out` must reference `out_cap`
 * bytes if non-NULL.
 */
int meow_patch_config(const char *source_yaml, int mixed_port, char *out, int out_cap);

/**
 * Start tun2socks with a Swift-owned egress callback. The ingest side is
 * driven by `meow_tun_ingest`; the tunnel uses an internal mpsc queue so
 * there's no file descriptor between Swift and Rust.
 *
 * Returns 0 on success, -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `ctx` is opaque to Rust but must remain valid for any dispatch that occurs
 * between this call and `meow_tun_stop`. `write_cb` must be a non-null C
 * function pointer that stays valid for the lifetime of the tunnel.
 */
int meow_tun_start(void *ctx, MeowWritePacket write_cb);

/**
 * Feed a raw IP packet from `NEPacketTunnelFlow.readPackets` into the
 * netstack. Returns 0 if the packet was queued (or dropped under backpressure),
 * -1 if tun2socks isn't running. Non-blocking; callers shouldn't hold
 * `readPackets` completion handlers waiting.
 *
 * # Safety
 * `data` must reference `len` bytes of readable memory.
 */
int meow_tun_ingest(const uint8_t *data, uintptr_t len);

/**
 * Stop the tun2socks task. Idempotent. Fire-and-forget: the run task drains
 * on the runtime after this returns. Use for suspend/resume, where the egress
 * `ctx` is retained for reuse.
 */
void meow_tun_stop(void);

/**
 * Stop the tun2socks task and BLOCK until its run task (including the egress
 * callback loop) has fully torn down. Once this returns, the egress write
 * callback is guaranteed never to fire again, so the caller may safely
 * release the `ctx` it passed to `meow_tun_start` — required for a terminal
 * stop, where releasing the writer while the egress task is still draining
 * is a use-after-free. Call from a NON-runtime thread (the Swift tunnel
 * control queue). Idempotent.
 */
void meow_tun_stop_blocking(void);

/**
 * Abort every in-flight TCP flow tracked by tun2socks. This is an
 * emergency diagnostic/teardown hook for dropping stale flows without
 * tearing down the engine or the TUN itself.
 *
 * Each abort cancels the dispatch_tcp future, which drops the netstack
 * stream side and (via `ConnectionGuard::drop` inside meow-tunnel)
 * removes the corresponding entry from `Statistics.connections` —
 * keeping our flow registry and meow's state in sync.
 *
 * UDP flows are intentionally untouched: they're connectionless from
 * the app's perspective, meow's NAT entries time out on their own,
 * and aborting them mid-flight would pointlessly drop in-flight DNS
 * replies during the interface flip.
 *
 * Returns the number of flows aborted.
 */
int meow_tun_close_all_tcp_flows(void);

/**
 * Set the TCP accept-side cap. Bounds the number of concurrent
 * `dispatch_tcp` tasks live at once, which is the dominant factor in
 * peak FFI RSS under burst (1000+ concurrent dispatches each carrying
 * per-flow Metadata, Box<dyn ProxyConn>, meow outbound dial state,
 * and netstack ring buffers can push the extension past the 50 MiB
 * jetsam cap). Default 128.
 *
 * Takes effect on the next `meow_tun_start`. Calls during a live
 * tunnel are accepted but do not resize the running semaphore.
 *
 * Returns 0 on success, -1 on invalid input (`cap == 0`, which would
 * deadlock the accept loop).
 */
int meow_tun_set_accept_cap(int cap);

/**
 * Read the currently-configured TCP accept cap. Reflects the value the
 * next `meow_tun_start` will use; does not query the running semaphore.
 */
int meow_tun_accept_cap(void);

/**
 * Set the per-flow dial deadline, in milliseconds. Bounds the time
 * `dispatch_tcp` waits for the relay's first byte of progress on the
 * netstack stream before declaring the dial hung and dropping the
 * future. See docs/INVESTIGATION-2026-05-18-tcp-direct-rule-disconnect.md
 * for context.
 *
 * Default 10000 ms. Pass `0` to disable the watchdog (relies on the
 * 30 s idle sweeper to reap stuck flows). Negative values are rejected.
 *
 * Takes effect on the next flow accepted; does not abort in-flight
 * flows mid-wait.
 *
 * Returns 0 on success, -1 on invalid input.
 */
int meow_tun_set_dial_deadline_ms(int ms);

/**
 * Read the currently-configured per-flow dial deadline, in
 * milliseconds. `0` means the watchdog is disabled.
 */
int meow_tun_dial_deadline_ms(void);

/**
 * Set the per-UDP-session first-reply deadline, in milliseconds. The
 * symmetric counterpart to `meow_tun_set_dial_deadline_ms` for the UDP
 * path — UDP doesn't connect, but iOS auto-bypass can silently drop
 * the outbound sendto when the scoped-routing cache is stale, leaving
 * the reply reader parked on `read_packet` forever. Bounding the
 * *first* reply lets us evict a dead session so the next app datagram
 * dispatches a fresh socket against a refreshed iOS route.
 *
 * Default 10000 ms. Pass `0` to disable the deadline (legacy unbounded
 * behaviour — relies on meow's NAT-table TTL to reap idle sessions).
 * Negative values are rejected.
 *
 * Takes effect on the next UDP session whose reply reader spawns;
 * existing readers keep their captured deadline.
 *
 * Returns 0 on success, -1 on invalid input.
 */
int meow_tun_set_udp_first_reply_deadline_ms(int ms);

/**
 * Read the currently-configured UDP first-reply deadline, in
 * milliseconds. `0` means the deadline is disabled.
 */
int meow_tun_udp_first_reply_deadline_ms(void);

/**
 * Set the per-TCP-flow idle TTL, in milliseconds. The complement to
 * `meow_tun_set_dial_deadline_ms` for flows whose dial *succeeded* but
 * then went permanently quiet — e.g. the upstream proxy EOF'd an idle
 * connection and the (suspended) app never FINs back, parking the relay
 * forever while it pins an accept-cap permit and an lwip pcb. Hours of
 * such accumulation exhausts the accept cap and the tunnel stops
 * passing new TCP flows ("connected but no traffic").
 *
 * Default 600000 ms (10 min). Raised from the conventional 5-min proxy
 * idle timeout so no-keepalive server-push channels with multi-minute quiet
 * gaps aren't reaped while alive (2026-06-14 long-lived-TCP audit). Pass `0`
 * to disable the sweeper. Negative values are rejected.
 *
 * Takes effect on the sweeper's next 30 s tick; no restart needed.
 *
 * Returns 0 on success, -1 on invalid input.
 */
int meow_tun_set_tcp_idle_ttl_ms(int ms);

/**
 * Read the currently-configured TCP idle TTL, in milliseconds. `0`
 * means the sweeper is disabled.
 */
int meow_tun_tcp_idle_ttl_ms(void);

/**
 * Enable or disable "block HTTP/3 (QUIC)". Default OFF (0): current
 * behaviour is preserved. When enabled (non-zero) the tunnel drops
 * outbound UDP datagrams to destination port 443 (QUIC's transport) and
 * answers SVCB (64) / HTTPS (65) DNS queries NOERROR-empty from the
 * intercept itself (no h3/SvcParams advertisement), forcing clients onto
 * the A / fake-IPv4 + TCP path.
 *
 * At the FFI layer the new value applies immediately to subsequent UDP
 * datagrams and DNS queries (the backing flag is a plain atomic). The
 * meow-ios app only invokes this at tunnel start, so toggling the user
 * preference applies on the next tunnel (re)connect — same as allowLan.
 *
 * Returns 0 unconditionally.
 */
int meow_tun_set_block_http3(int enabled);

/**
 * Read whether "block HTTP/3 (QUIC)" is currently enabled. Returns 1 if
 * enabled, 0 otherwise.
 */
int meow_tun_block_http3(void);

/**
 * Resident memory size of the FFI's containing process, in bytes. Same
 * number macOS jetsam compares against the 50 MiB PacketTunnel cap, so
 * Swift can poll this to chart the on-device RSS curve during a stress
 * run without depending on Instruments. Returns 0 on platforms where
 * the mach call isn't available (non-Apple targets).
 */
uint64_t meow_resident_bytes(void);

#endif  /* MEOW_CORE_H */
