// Generated by cbindgen — do not edit by hand.

#ifndef MIHOMO_CORE_H
#define MIHOMO_CORE_H

#pragma once

/* Regenerate with `cbindgen --config cbindgen.toml --output include/mihomo_core.h` */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize logging. Safe to call more than once.
 */
void meow_core_init(void);

/**
 * Set the app-group container path where config.yaml and cache files live.
 * `dir` may be NULL or empty.
 *
 * # Safety
 * `dir` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void meow_core_set_home_dir(const char *dir);

/**
 * Return the last error message for the calling thread. The pointer is
 * owned by the crate and valid until the next error is set on the same
 * thread — copy immediately if retention is needed.
 */
const char *meow_core_last_error(void);

/**
 * Start the mihomo-rust engine using the YAML at `config_path`. Idempotent.
 * Returns 0 on success, -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `config_path` must point to a NUL-terminated UTF-8 string.
 */
int meow_engine_start(const char *config_path);

/**
 * Stop the mihomo-rust engine. Idempotent.
 */
void meow_engine_stop(void);

/**
 * Returns 1 if the engine is running, 0 otherwise.
 */
int meow_engine_is_running(void);

/**
 * Validate a Clash YAML config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `yaml` must point to `len` bytes of UTF-8.
 */
int meow_engine_validate_config(const char *yaml, int len);

/**
 * Write cumulative upload/download byte counters. Safe to call before
 * `meow_engine_start` — returns zero counters.
 *
 * # Safety
 * Pointers, if non-NULL, must reference writable 64-bit integer slots.
 */
void meow_engine_traffic(int64_t *out_upload, int64_t *out_download);

/**
 * Convert a subscription body (Clash YAML, or base64-wrapped / plain v2rayN
 * URI list) to Clash YAML. Writes NUL-terminated UTF-8 into `out`/`out_cap`.
 * Returns the total bytes needed (not counting NUL); if the return exceeds
 * `out_cap`, the output was truncated — allocate `ret + 1` and retry.
 * Returns -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `body` must reference `len` bytes; `out` must reference `out_cap` bytes
 * if non-NULL.
 */
int meow_engine_convert_subscription(const char *body, int len, char *out, int out_cap);

/**
 * Measure direct TCP connect latency to `host:port`. Writes elapsed ms into
 * `out_ms`; returns 0 on success, -1 on error.
 *
 * # Safety
 * `host` must be NUL-terminated; `out_ms` must be writable.
 */
int meow_engine_test_direct_tcp(const char *host, int port, int timeout_ms, int64_t *out_ms);

/**
 * HTTP reachability via the engine's default (direct) adapter.
 *
 * # Safety
 * `url` must be NUL-terminated; outputs may be NULL.
 */
int meow_engine_test_proxy_http(const char *url, int timeout_ms, int *out_status, int64_t *out_ms);

/**
 * Resolve `host` via the engine resolver. Writes comma-separated IPs into
 * `out`/`out_cap` (same truncation rules as `meow_engine_convert_subscription`).
 *
 * # Safety
 * `host` must be NUL-terminated; `out` must reference `out_cap` bytes if
 * non-NULL.
 */
int meow_engine_test_dns(const char *host, int timeout_ms, char *out, int out_cap);

/**
 * Start tun2socks on `fd`. `socks_port` / `dns_port` are reserved for API
 * compatibility; the in-process dispatcher ignores both. Returns 0 on
 * success, -1 on error (inspect `meow_core_last_error`).
 */
int meow_tun_start(int fd, int socks_port, int dns_port);

/**
 * Stop the tun2socks task. Idempotent.
 */
void meow_tun_stop(void);

#endif  /* MIHOMO_CORE_H */
