// Generated by cbindgen — do not edit by hand.

#ifndef MIHOMO_CORE_H
#define MIHOMO_CORE_H

#pragma once

/* Regenerate with `cbindgen --config cbindgen.toml --output include/mihomo_core.h` */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C-compatible egress callback. Called from the tokio runtime whenever
 * tun2socks produces a packet bound for Swift's `NEPacketTunnelFlow`. Swift
 * guarantees `ctx` remains live between `meow_tun_start` and `meow_tun_stop`.
 */
typedef void (*MeowWritePacket)(void *ctx, const uint8_t *data, uintptr_t len);

/**
 * Initialize logging. Safe to call more than once.
 */
void meow_core_init(void);

/**
 * Set the app-group container path where config.yaml and cache files live.
 * `dir` may be NULL or empty.
 *
 * Also exports `$XDG_CONFIG_HOME=<dir>` into the process env so `mihomo-config`
 * finds its GeoIP database at `<dir>/mihomo/Country.mmdb` (upstream mihomo's
 * resolution order is `$XDG_CONFIG_HOME/mihomo/` → `$HOME/.config/mihomo/`).
 * iOS sandbox HOME has no `.config`, so the env var is how the bundled Country.mmdb
 * lands on the engine's load path.
 *
 * # Safety
 * `dir` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void meow_core_set_home_dir(const char *dir);

/**
 * Return the last error message for the calling thread. The pointer is
 * owned by the crate and valid until the next error is set on the same
 * thread — copy immediately if retention is needed.
 */
const char *meow_core_last_error(void);

/**
 * Start the mihomo-rust engine using the YAML at `config_path`. Idempotent.
 * Returns 0 on success, -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `config_path` must point to a NUL-terminated UTF-8 string.
 */
int meow_engine_start(const char *config_path);

/**
 * Stop the mihomo-rust engine. Idempotent.
 */
void meow_engine_stop(void);

/**
 * Returns 1 if the engine is running, 0 otherwise.
 */
int meow_engine_is_running(void);

/**
 * Validate a Clash YAML config. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `yaml` must point to `len` bytes of UTF-8.
 */
int meow_engine_validate_config(const char *yaml, int len);

/**
 * Return the number of currently active (in-flight) TCP flows dispatched
 * through the tun2socks layer. Useful for diagnosing connection accumulation.
 */
int64_t meow_active_tcp_conns(void);

/**
 * Write cumulative upload/download byte counters. Safe to call before
 * `meow_engine_start` — returns zero counters.
 *
 * # Safety
 * Pointers, if non-NULL, must reference writable 64-bit integer slots.
 */
void meow_engine_traffic(int64_t *out_upload, int64_t *out_download);

/**
 * Convert a subscription body (Clash YAML, or base64-wrapped / plain v2rayN
 * URI list) to Clash YAML. Writes NUL-terminated UTF-8 into `out`/`out_cap`.
 * Returns the total bytes needed (not counting NUL); if the return exceeds
 * `out_cap`, the output was truncated — allocate `ret + 1` and retry.
 * Returns -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `body` must reference `len` bytes; `out` must reference `out_cap` bytes
 * if non-NULL.
 */
int meow_engine_convert_subscription(const char *body, int len, char *out, int out_cap);

/**
 * Measure direct TCP connect latency to `host:port`. Writes elapsed ms into
 * `out_ms`; returns 0 on success, -1 on error.
 *
 * # Safety
 * `host` must be NUL-terminated; `out_ms` must be writable.
 */
int meow_engine_test_direct_tcp(const char *host, int port, int timeout_ms, int64_t *out_ms);

/**
 * HTTP reachability via the engine's default (direct) adapter.
 *
 * # Safety
 * `url` must be NUL-terminated; outputs may be NULL.
 */
int meow_engine_test_proxy_http(const char *url, int timeout_ms, int *out_status, int64_t *out_ms);

/**
 * Resolve `host` via the engine resolver. Writes comma-separated IPs into
 * `out`/`out_cap` (same truncation rules as `meow_engine_convert_subscription`).
 *
 * # Safety
 * `host` must be NUL-terminated; `out` must reference `out_cap` bytes if
 * non-NULL.
 */
int meow_engine_test_dns(const char *host, int timeout_ms, char *out, int out_cap);

/**
 * Configure the trusted plain-TCP DNS upstream pool from the iOS Settings
 * view. `csv` is a comma-/whitespace-separated list of `host` or
 * `host:port` entries (port defaults to 53); empty / NULL / parse-failed
 * input falls back to the built-in defaults (1.1.1.1 / 8.8.8.8).
 *
 * Call this before `meow_tun_start` — the upstream list is read once
 * inside `init_dns_client`. Writes are still safe at runtime; they take
 * effect on the next tunnel start.
 *
 * # Safety
 * `csv`, if non-NULL, must be a NUL-terminated UTF-8 C string.
 */
int meow_dns_set_upstreams(const char *csv);

/**
 * Patch a Clash YAML config for iOS: strips `dns`, `subscriptions`, `secret`;
 * pins `mixed-port` and `external-controller`; injects `geox-url` when absent.
 * Writes NUL-terminated UTF-8 into `out`/`out_cap`. Returns bytes needed (excl
 * NUL) on success; callers allocate `ret + 1` and retry if `ret >= out_cap`.
 * Returns -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `source_yaml` must be NUL-terminated UTF-8. `out` must reference `out_cap`
 * bytes if non-NULL.
 */
int meow_patch_config(const char *source_yaml, int mixed_port, char *out, int out_cap);

/**
 * Start tun2socks with a Swift-owned egress callback. The ingest side is
 * driven by `meow_tun_ingest`; the tunnel uses an internal mpsc queue so
 * there's no file descriptor between Swift and Rust.
 *
 * Returns 0 on success, -1 on error (inspect `meow_core_last_error`).
 *
 * # Safety
 * `ctx` is opaque to Rust but must remain valid for any dispatch that occurs
 * between this call and `meow_tun_stop`. `write_cb` must be a non-null C
 * function pointer that stays valid for the lifetime of the tunnel.
 */
int meow_tun_start(void *ctx, MeowWritePacket write_cb);

/**
 * Feed a raw IP packet from `NEPacketTunnelFlow.readPackets` into the
 * netstack. Returns 0 if the packet was queued (or dropped under backpressure),
 * -1 if tun2socks isn't running. Non-blocking; callers shouldn't hold
 * `readPackets` completion handlers waiting.
 *
 * # Safety
 * `data` must reference `len` bytes of readable memory.
 */
int meow_tun_ingest(const uint8_t *data, uintptr_t len);

/**
 * Stop the tun2socks task. Idempotent.
 */
void meow_tun_stop(void);

#endif  /* MIHOMO_CORE_H */
